import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Noto_Sans } from 'next/font/google'

const notoSans = Noto_Sans({
  weight: ['400', '500', '600', '700'],
  style: ['italic', 'normal'],
  subsets: ['latin']
 })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={notoSans.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
